# Generated by Django 5.1.6 on 2025-03-13 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short biography of the artist."
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("creation_date", models.DateField(blank=True, null=True)),
                ("discovered_date", models.DateField(blank=True, null=True)),
                (
                    "medium",
                    models.CharField(
                        help_text="E.g. Oil on Canvas, Sculpture, Digital Art",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="artworks/"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_for_sale", models.BooleanField(default=False)),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Width in centimeters",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Depth in centimeters (for 3D art)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="artwork.artist",
                    ),
                ),
            ],
        ),
    ]
